function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 30-Jun-2023 09:04:34

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'DisplayName','(x, y)',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
xlabel('$x_{ball}$ [m]')
ylabel('$y_{ball}$ [m]')
% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[-0.195 0.195]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot1,[-0.195 0.195]);
box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.693749998480315 0.762539692356608 0.138928572569575 0.0457142865771338],...
    'Interpreter','none');

